name: Update Weather Data

on:
  schedule:
    # Rennt immer noch zweimal pro Stunde, aber zu Zeiten, wo GitHubs Server chillen
    - cron: '12,42 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Jetzt stürzen die Skripte nicht mehr nach 6 Sekunden ab!
      - name: Run Scripts
        run: |
          python conditions.py
          python fetch.py
          
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          if ! git diff --cached --quiet; then
            git commit -m "Update weather data"
            git push origin main
          else
            echo "Keine Änderungen vorhanden. Überspringe Commit und Push."
          fi
